# Required
version: 2

build:
  os: ubuntu-20.04
  apt_packages:
    - ca-certificates  # Explicitly install to update ca-certificates 
    - apt-https-transport

formats: []

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/source/conf.py

python:
   install:
   - requirements: docs/requirements.txt
